In [2]:
import os

os.chdir("/Users/anitanam/optical_materials_ml")

print(os.getcwd())

/Users/anitanam/optical_materials_ml

In [3]:
import pandas as pd

jarvis = pd.read_parquet(
    "data/raw/jarvis_dft3d.parquet"
)

jarvis.shape

(75993, 12)

In [4]:
jarvis.columns

Index(['jid', 'formula', 'optb88vdw_bandgap', 'mbj_bandgap',
       'formation_energy_peratom', 'ehull', 'epsx', 'epsy', 'epsz', 'slme',
       'refractive_index', 'source_db'],
      dtype='object')

In [5]:
import os

root = "/Users/anitanam/optical_materials_ml"
for folder in ["data/raw", "data/processed", "notebooks/data/processed"]:
    print(f"\n--- {folder} ---")
    full = os.path.join(root, folder)
    for name in sorted(os.listdir(full)):
        print(name)

--- data/raw ---
jarvis_dft3d.parquet
matbench_dielectric.parquet
matbench_expt_gap.parquet
matbench_mp_gap.parquet
mp_dielectric.parquet
mp_summary.parquet

--- data/processed ---

--- notebooks/data/processed ---
bandgap_features.parquet
bandgap_test.parquet
bandgap_train.parquet
refractive_index_features.parquet
ri_final.parquet
ri_final_no_density.parquet
ri_final_with_density.parquet
ri_master.parquet

In [6]:
# Structure Modeling Investigation

Current finding:

- jarvis_dft3d.parquet contains only property information.
- No crystal structure representation is present.
- CGCNN/M3GNet/LIGNN require crystal structures.
- Need structure source before proceeding.

Next action:
Determine source of crystal structures (JARVIS API, CIF files, MP structures, etc.).

SyntaxError: invalid syntax (3251509037.py, line 3)

In [7]:
jarvis[["jid", "formula"]].head()

           jid   formula
0  JVASP-90856  TiCuSiAs
1  JVASP-86097      DyB6
2  JVASP-64906   Be2OsRu
3  JVASP-98225       KBi
4     JVASP-10      VSe2

In [8]:
try:
    from jarvis.db.figshare import data
    print("JARVIS package available")
except Exception as e:
    print(e)

No module named 'jarvis'

In [9]:
from jarvis.db.figshare import data, get_jid_data

# Load the full 3D JARVIS dataset once
dft3d = data("dft_3d")

# Test one ID
rec = get_jid_data(jid="JVASP-10", dataset="dft_3d")
print(rec.keys())

ModuleNotFoundError: No module named 'jarvis'

In [10]:
import sys

print(sys.executable)

/opt/homebrew/Cellar/jupyterlab/4.5.8_1/libexec/bin/python

In [11]:
from jarvis.db.figshare import data, get_jid_data

print("JARVIS installed")

ModuleNotFoundError: No module named 'jarvis'

In [1]:
from jarvis.db.figshare import data, get_jid_data

print("JARVIS installed")

JARVIS installed

In [2]:
from jarvis.db.figshare import get_jid_data
from jarvis.core.atoms import Atoms

# test one real JARVIS ID
rec = get_jid_data(jid="JVASP-10", dataset="dft_3d")

print(rec.keys())
print(rec.get("jid"))
print(rec.get("formula"))

# if atoms is present, convert it into a JARVIS Atoms object
if "atoms" in rec:
    atoms = Atoms.from_dict(rec["atoms"])
    print(atoms)

Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699

100%|██████████| 48.4M/48.4M [00:22<00:00, 2.12MiB/s]

Loading the zipfile...
Loading completed.
dict_keys(['jid', 'spg_number', 'spg_symbol', 'formula', 'formation_energy_peratom', 'func', 'optb88vdw_bandgap', 'atoms', 'slme', 'magmom_oszicar', 'spillage', 'elastic_tensor', 'effective_masses_300K', 'kpoint_length_unit', 'maxdiff_mesh', 'maxdiff_bz', 'encut', 'optb88vdw_total_energy', 'epsx', 'epsy', 'epsz', 'mepsx', 'mepsy', 'mepsz', 'modes', 'magmom_outcar', 'max_efg', 'avg_elec_mass', 'avg_hole_mass', 'icsd', 'dfpt_piezo_max_eij', 'dfpt_piezo_max_dij', 'dfpt_piezo_max_dielectric', 'dfpt_piezo_max_dielectric_electronic', 'dfpt_piezo_max_dielectric_ionic', 'max_ir_mode', 'min_ir_mode', 'n-Seebeck', 'p-Seebeck', 'n-powerfact', 'p-powerfact', 'ncond', 'pcond', 'nkappa', 'pkappa', 'ehull', 'Tc_supercon', 'dimensionality', 'efg', 'xml_data_link', 'typ', 'exfoliation_energy', 'spg', 'crys', 'density', 'poisson', 'raw_files', 'nat', 'bulk_modulus_kv', 'shear_modulus_gv', 'mbj_bandgap', 'hse_gap', 'reference', 'search'])
JVASP-10
VSe2
System
1.0
1.6777483798834445 -2.9059452409270157 -1.1e-15
1.6777483798834438 2.9059452409270126 -7e-16
-6.5e-15 -8e-16 6.220805465667012
V Se
1 2
direct
0.0 0.0 0.0 V
0.6666669999999968 0.3333330000000032 0.7479606991085345 Se
0.3333330000000032 0.6666669999999968 0.252039300891465 Se

In [3]:
jids = jarvis["jid"].head(5).tolist()
records = [get_jid_data(jid=j, dataset="dft_3d") for j in jids]

for r in records:
    print(r["jid"], r.keys())

NameError: name 'jarvis' is not defined

In [5]:
import os

os.chdir("/Users/anitanam/optical_materials_ml")

print(os.getcwd())

/Users/anitanam/optical_materials_ml

In [6]:
import pandas as pd

jarvis = pd.read_parquet(
    "data/raw/jarvis_dft3d.parquet"
)

jarvis.shape

(75993, 12)

In [7]:
jids = jarvis["jid"].head(5).tolist()

records = [
    get_jid_data(
        jid=j,
        dataset="dft_3d"
    )
    for j in jids
]

for r in records:
    print(r["jid"], r["formula"])

Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
JVASP-90856 TiCuSiAs
JVASP-86097 DyB6
JVASP-64906 Be2OsRu
JVASP-98225 KBi
JVASP-10 VSe2

In [8]:
sample = records[0]

type(sample["atoms"])

dict

In [9]:
sample["atoms"]

{'lattice_mat': [[3.566933224304235, 0.0, -0.0],
  [0.0, 3.566933224304235, -0.0],
  [-0.0, -0.0, 9.397075454186664]],
 'coords': [[2.6751975000000003, 2.6751975000000003, 7.376101754328542],
  [0.8917325, 0.8917325, 2.0209782456714573],
  [0.8917325, 2.6751975000000003, 4.69854],
  [2.6751975000000003, 0.8917325, 4.69854],
  [0.8917325, 2.6751975000000003, 0.0],
  [2.6751975000000003, 0.8917325, 0.0],
  [2.6751975000000003, 2.6751975000000003, 2.8894795605846353],
  [0.8917325, 0.8917325, 6.507600439415366]],
 'elements': ['Ti', 'Ti', 'Cu', 'Cu', 'Si', 'Si', 'As', 'As'],
 'abc': [3.56693, 3.56693, 9.39708],
 'angles': [90.0, 90.0, 90.0],
 'cartesian': True,
 'props': ['', '', '', '', '', '', '', '']}

In [10]:
import pandas as pd

structure_df = pd.DataFrame([
    {
        "jid": r["jid"],
        "formula": r["formula"],
        "atoms": r["atoms"]
    }
    for r in records
])

structure_df.head()

           jid   formula                                              atoms
0  JVASP-90856  TiCuSiAs  {'lattice_mat': [[3.566933224304235, 0.0, -0.0...
1  JVASP-86097      DyB6  {'lattice_mat': [[4.089078911208881, 0.0, 0.0]...
2  JVASP-64906   Be2OsRu  {'lattice_mat': [[-1.833590720595598, 1.833590...
3  JVASP-98225       KBi  {'lattice_mat': [[7.2963518353359165, 0.0, 0.0...
4     JVASP-10      VSe2  {'lattice_mat': [[1.6777483798834445, -2.90594...

In [11]:
structure_df.iloc[0]["atoms"].keys()

dict_keys(['lattice_mat', 'coords', 'elements', 'abc', 'angles', 'cartesian', 'props'])

In [13]:
import os

print(os.getcwd())

for root, dirs, files in os.walk("."):
    for f in files:
        if "ri_final" in f:
            print(os.path.join(root, f))

/Users/anitanam/optical_materials_ml
./notebooks/data/processed/ri_final_with_density.parquet
./notebooks/data/processed/ri_final.parquet
./notebooks/data/processed/ri_final_no_density.parquet

In [14]:
from jarvis.db.figshare import data

dft3d = data("dft_3d")

print(len(dft3d))

Obtaining 3D dataset 94k ...
Reference:https://doi.org/10.1016/j.commatsci.2025.114063
Other versions:https://doi.org/10.6084/m9.figshare.6815699
Loading the zipfile...
Loading completed.
93902

In [15]:
structure_lookup = {
    x["jid"]: x["atoms"]
    for x in dft3d
}

In [16]:
import pandas as pd

ri_final = pd.read_parquet(
    "notebooks/data/processed/ri_final_no_density.parquet"
)

ri_final.shape

(32341, 140)

In [17]:
jarvis = pd.read_parquet(
    "data/raw/jarvis_dft3d.parquet"
)

jarvis.shape

(75993, 12)

In [19]:
import pandas as pd
from pymatgen.core import Composition

def to_reduced_formula(formula):
    try:
        return Composition(formula).reduced_formula
    except:
        return None

# make sure JARVIS has reduced_formula
jarvis["reduced_formula"] = jarvis["formula"].apply(to_reduced_formula)

# one representative JID per reduced formula
jarvis_rf = (
    jarvis[["reduced_formula", "jid"]]
    .dropna(subset=["reduced_formula"])
    .drop_duplicates(subset=["reduced_formula"], keep="first")
)

# merge using reduced_formula, not formula
ri_structure = ri_final.merge(
    jarvis_rf,
    on="reduced_formula",
    how="left"
)

ri_structure["atoms"] = ri_structure["jid"].map(structure_lookup)

print(ri_structure.shape)
print(ri_structure["atoms"].notna().sum())

/opt/homebrew/Cellar/python@3.14/3.14.6/Frameworks/Python.framework/Versions/3.14/lib/python3.14/functools.py:1126: UserWarning: No Pauling electronegativity for He. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)
/opt/homebrew/Cellar/python@3.14/3.14.6/Frameworks/Python.framework/Versions/3.14/lib/python3.14/functools.py:1126: UserWarning: No Pauling electronegativity for Ar. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)
/opt/homebrew/Cellar/python@3.14/3.14.6/Frameworks/Python.framework/Versions/3.14/lib/python3.14/functools.py:1126: UserWarning: No Pauling electronegativity for Ne. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  val = self.func(instance)

(32341, 142)
32341

In [20]:
ri_structure["atoms"].notna().mean()

np.float64(1.0)

In [21]:
ri_structure.to_parquet(
    "notebooks/data/processed/ri_structure_dataset.parquet",
    index=False
)

In [22]:
import os

os.path.exists(
    "notebooks/data/processed/ri_structure_dataset.parquet"
)

True

In [23]:
# Structure Dataset Complete

Dataset size:
- 32,341 materials

Structure coverage:
- 32,341 / 32,341 (100%)

Contents:
- Formula
- JVASP ID
- Crystal Structure
- Refractive Index
- Band Gap
- Formation Energy
- Magpie Features

Next step:
Evaluate structure-based models:
- LIGNN
- CGCNN
- M3GNet

SyntaxError: invalid syntax (459995751.py, line 3)

In [24]:
from jarvis.core.atoms import Atoms

atoms = Atoms.from_dict(
    ri_structure.iloc[0]["atoms"]
)

atoms

System
1.0
3.566933224304235 0.0 -0.0
0.0 3.566933224304235 -0.0
-0.0 -0.0 9.397075454186664
Ti Cu Si As
2 2 2 2
direct
0.7500000000000001 0.7500000000000001 0.784935507022239 Ti
0.25 0.25 0.2150644929777609 Ti
0.25 0.7500000000000001 0.5 Cu
0.7500000000000001 0.25 0.5 Cu
0.25 0.7500000000000001 0.0 Si
0.7500000000000001 0.25 0.0 Si
0.7500000000000001 0.7500000000000001 0.3074869598412097 As
0.25 0.25 0.6925130401587904 As

In [25]:
atoms.num_atoms

8

In [26]:
atoms.composition

OrderedDict({'Ti': 2, 'Cu': 2, 'Si': 2, 'As': 2})

In [27]:
ri_structure.to_parquet(
    "notebooks/data/processed/ri_structure_dataset.parquet",
    index=False
)

In [28]:
import os

os.path.exists(
    "notebooks/data/processed/ri_structure_dataset.parquet"
)

True